### ISSUE TITLE
Nuget package is not up-to-date

### ISSUE THREAD

**Issue by MorganeJosserand** [SourceCodeBackup/GenCode128#4]
Hi,
First, many thanks for your work ! This project is really useful !
We noticed that the nuget package has some differences in the code compared to the master branch.
Basically, we get the [System.IndexOutOfRangeException](https://www.codeproject.com/Messages/2212824/System-IndexOutOfRangeException) when using the nuget package. This error is fixed in the master branch when testing the demo.
Is it possible to create an up-to-date nuget package ?
Thanks a lot,
Morgane

**Comment by NikolayIT** [comment]
The package is uploaded: https://www.nuget.org/packages/GenCode128/2.0.0

**Comment by MorganeJosserand** [comment]
Wow ! Thank you so much for the quick update, it is truly appreciated 👍

**Comment by NikolayIT** [comment]
You are welcome!
